"""remove SMS fields opted_out message_id status

Revision ID: 60dc3ae4da5d
Revises: 65e621b64ab5
Create Date: 2026-03-17 17:24:13.692727

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60dc3ae4da5d"
down_revision: str | Sequence[str] | None = "65e621b64ab5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "opted_out")
    op.drop_column("messages", "status")
    op.drop_column("messages", "message_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("message_id", sa.VARCHAR(length=255), nullable=True)
    )
    op.add_column(
        "messages", sa.Column("status", sa.VARCHAR(length=50), nullable=False)
    )
    op.add_column("customers", sa.Column("opted_out", sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
